### ISSUE TITLE
App crashes after selecting add action from list

### ISSUE THREAD

**Issue by asadana** [asadana/IGotThis#1]
> 12-26 21:50:51.796 25651-25651/? I/libpersona: KNOX_SDCARD checking this for 10203
> 12-26 21:50:51.796 25651-25651/? E/Zygote: v2
> 12-26 21:50:51.796 25651-25651/? I/libpersona: KNOX_SDCARD not a persona
> 12-26 21:50:51.796 25651-25651/? W/SELinux: Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0031
> 12-26 21:50:51.796 25651-25651/? E/Zygote: accessInfo : 0
> 12-26 21:50:51.806 25651-25651/? W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.boulder.igotthis 
> 12-26 21:50:51.806 25651-25651/? I/art: Late-enabling -Xcheck:jni
> 12-26 21:50:51.846 25651-25651/? D/TimaKeyStoreProvider: TimaSignature is unavailable
> 12-26 21:50:51.846 25651-25651/? D/ActivityThread: Added TimaKeyStore provider
> 12-26 21:50:51.876 25651-25651/com.boulder.igotthis W/ResourcesManager: getTopLevelResources: /data/app/com.boulder.igotthis-2/base.apk / 1.0 running in com.boulder.igotthis rsrc of package null
> 12-26 21:50:51.886 25651-25651/com.boulder.igotthis W/System: ClassLoader referenced unknown path: /data/app/com.boulder.igotthis-2/lib/arm
> 12-26 21:50:51.936 25651-25651/com.boulder.igotthis W/ResourcesManager: getTopLevelResources: /data/app/com.boulder.igotthis-2/base.apk / 1.0 running in com.boulder.igotthis rsrc of package null
> 12-26 21:50:51.946 25651-25651/com.boulder.igotthis W/ResourcesManager: getTopLevelResources: /data/app/com.boulder.igotthis-2/base.apk / 1.0 running in com.boulder.igotthis rsrc of package null
> 12-26 21:50:51.956 25651-25651/com.boulder.igotthis W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
> 12-26 21:50:52.026 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.026 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.046 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.046 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.046 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.056 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.056 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.056 25651-25651/com.boulder.igotthis D/TextView: setTypeface with style : 0
> 12-26 21:50:52.066 25651-25651/com.boulder.igotthis D/com.boulder.igotthis.TaskCreation: init
> 12-26 21:50:52.096 25651-25651/com.boulder.igotthis D/SecWifiDisplayUtil: Metadata value : none
> 12-26 21:50:52.096 25651-25651/com.boulder.igotthis D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{ce332db I.E...... R.....ID 0,0-0,0}
> 12-26 21:50:52.096 25651-25681/com.boulder.igotthis D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
> 12-26 21:50:52.156 25651-25681/com.boulder.igotthis I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ia10634f51b)
>                                                                   OpenGL ES Shader Compiler Version: E031.29.00.00
>                                                                   Build Date: 01/28/16 Thu
>                                                                   Local Branch: ss
>                                                                   Remote Branch: 
>                                                                   Local Patches: 
>                                                                   Reconstruct Branch: 
> 12-26 21:50:52.156 25651-25681/com.boulder.igotthis D/libEGL: eglInitialize EGLDisplay = 0xae07f7c4
> 12-26 21:50:52.156 25651-25681/com.boulder.igotthis I/OpenGLRenderer: Initialized EGL, version 1.4
> 12-26 21:50:52.206 25651-25651/com.boulder.igotthis D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
> 12-26 21:50:52.316 25651-25651/com.boulder.igotthis I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c0cbfea time:167727074
> 12-26 21:50:52.516 25651-25651/com.boulder.igotthis I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c0cbfea time:167727273
> 12-26 21:50:55.776 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 0
> 12-26 21:50:55.846 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 1
> 12-26 21:50:56.826 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 0
> 12-26 21:50:56.916 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 1
> 12-26 21:50:58.016 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 0
> 12-26 21:50:58.126 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 1
> 12-26 21:50:58.386 25651-25651/com.boulder.igotthis D/AbsListView: Get MotionRecognitionManager
> 12-26 21:50:58.386 25651-25651/com.boulder.igotthis E/MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@a44a91c
> 12-26 21:50:58.386 25651-25651/com.boulder.igotthis E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@26ab925
> 12-26 21:50:58.386 25651-25651/com.boulder.igotthis E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@26ab925
> 12-26 21:50:58.396 25651-25651/com.boulder.igotthis D/SecWifiDisplayUtil: Metadata value : none
> 12-26 21:50:58.396 25651-25651/com.boulder.igotthis D/ViewRootImpl: #1 mView = android.widget.PopupWindow$PopupDecorView{86c48ab V.E...... ......I. 0,0-0,0}
> 12-26 21:50:58.476 25651-25651/com.boulder.igotthis D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
> 12-26 21:50:59.516 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 0
> 12-26 21:50:59.586 25651-25651/com.boulder.igotthis D/ViewRootImpl: ViewPostImeInputStage processPointer 1
> 12-26 21:50:59.656 25651-25651/com.boulder.igotthis D/ViewRootImpl: #3 mView = null
> 12-26 21:50:59.686 25651-25651/com.boulder.igotthis E/ViewRootImpl: sendUserActionEvent() mView == null
> 12-26 21:50:59.906 25651-25661/com.boulder.igotthis I/art: Background sticky concurrent mark sweep GC freed 51438(2MB) AllocSpace objects, 3(60KB) LOS objects, 31% free, 16MB/23MB, paused 33.305ms total 146.536ms
> 12-26 21:51:00.416 25651-25651/com.boulder.igotthis D/AndroidRuntime: Shutting down VM
> 12-26 21:51:01.426 25651-25661/com.boulder.igotthis I/art: Background partial concurrent mark sweep GC freed 169343(9MB) AllocSpace objects, 11(2MB) LOS objects, 20% free, 61MB/77MB, paused 23.285ms total 1.021s
> 12-26 21:51:02.126 25651-25661/com.boulder.igotthis I/art: Background partial concurrent mark sweep GC freed 23863(2MB) AllocSpace objects, 1(9MB) LOS objects, 14% free, 93MB/109MB, paused 1.753ms total 137.692ms
> 12-26 21:51:02.406 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.406 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.416 25651-25651/com.boulder.igotthis I/art: Alloc sticky concurrent mark sweep GC freed 118767(14MB) AllocSpace objects, 0(0B) LOS objects, 14% free, 93MB/109MB, paused 445us total 13.343ms
> 12-26 21:51:02.486 25651-25651/com.boulder.igotthis I/art: Waiting for a blocking GC Alloc
> 12-26 21:51:02.526 25651-25651/com.boulder.igotthis I/art: WaitForGcToComplete blocked for 45.080ms for cause Alloc
> 12-26 21:51:02.526 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.736 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.736 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.746 25651-25651/com.boulder.igotthis I/art: Alloc sticky concurrent mark sweep GC freed 82711(10MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 116MB/116MB, paused 359us total 10.105ms
> 12-26 21:51:02.746 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.806 25651-25651/com.boulder.igotthis I/art: Alloc partial concurrent mark sweep GC freed 11(1488B) AllocSpace objects, 1(33MB) LOS objects, 16% free, 83MB/99MB, paused 357us total 65.880ms
> 12-26 21:51:02.806 25651-25661/com.boulder.igotthis I/art: WaitForGcToComplete blocked for 76.809ms for cause Background
> 12-26 21:51:02.846 25651-25651/com.boulder.igotthis I/art: Waiting for a blocking GC Alloc
> 12-26 21:51:02.846 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.846 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.896 25651-25651/com.boulder.igotthis I/art: Alloc partial concurrent mark sweep GC freed 13(648B) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 356us total 47.980ms
> 12-26 21:51:02.896 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.906 25651-25661/com.boulder.igotthis I/art: WaitForGcToComplete blocked for 53.421ms for cause Background
> 12-26 21:51:02.906 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:02.966 25651-25651/com.boulder.igotthis I/art: Alloc concurrent mark sweep GC freed 9(12KB) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 358us total 63.152ms
> 12-26 21:51:02.966 25651-25651/com.boulder.igotthis I/art: Forcing collection of SoftReferences for 27MB allocation
> 12-26 21:51:02.966 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:03.016 25651-25651/com.boulder.igotthis I/art: Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 358us total 51.656ms
> 12-26 21:51:03.016 25651-25651/com.boulder.igotthis W/art: Throwing OutOfMemoryError "Failed to allocate a 28605692 byte allocation with 16777216 free bytes and 17MB until OOM"
> 12-26 21:51:03.016 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:03.016 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:03.026 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:03.076 25651-25651/com.boulder.igotthis I/art: Alloc partial concurrent mark sweep GC freed 6(192B) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 368us total 46.640ms
> 12-26 21:51:03.076 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:03.126 25651-25651/com.boulder.igotthis I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 357us total 51.122ms
> 12-26 21:51:03.126 25651-25651/com.boulder.igotthis I/art: Forcing collection of SoftReferences for 27MB allocation
> 12-26 21:51:03.126 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC Alloc
> 12-26 21:51:03.176 25651-25651/com.boulder.igotthis I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 357us total 51.482ms
> 12-26 21:51:03.176 25651-25651/com.boulder.igotthis I/art: Starting a blocking GC HomogeneousSpaceCompact
> 12-26 21:51:03.596 25651-25651/com.boulder.igotthis I/art: HomogeneousSpaceCompact marksweep + semispace GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 423.536ms total 423.536ms
> 12-26 21:51:03.596 25651-25651/com.boulder.igotthis W/art: Throwing OutOfMemoryError "Failed to allocate a 28605692 byte allocation with 16777216 free bytes and 17MB until OOM"
> 12-26 21:51:03.596 25651-25651/com.boulder.igotthis E/AndroidRuntime: Error reporting crash
>                                                                       java.lang.OutOfMemoryError: Failed to allocate a 28605692 byte allocation with 16777216 free bytes and 17MB until OOM
>                                                                           at java.lang.StringFactory.newStringFromChars(Native Method)
>                                                                           at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:629)
>                                                                           at java.lang.StringBuilder.toString(StringBuilder.java:663)
>                                                                           at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:60)
>                                                                           at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:44)
>                                                                           at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:92)
>                                                                           at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
>                                                                           at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
> 12-26 21:51:03.596 25651-25651/com.boulder.igotthis I/Process: Sending signal. PID: 25651 SIG: 9

**Comment by asadana** [comment]
There was a circular loop in ActionType that was causing the class, causing it to repeatedly request valueAt(). Fixed.
